### ISSUE TITLE
make.powerapps preview - setting icon and color

### ISSUE THREAD

**Issue by alex-mclachlan-silverbear** [MscrmTools/MscrmTools.Iconator#10]
Hi

The preview maker portal has the option to set the image and color for tables - from Solution > Tables > {your table} > Settings.

![image](https://user-images.githubusercontent.com/60521147/135323201-3b89d859-b0c0-4f67-a52d-ce17bf0ead98.png)

The image isn't pre-populated with the current .svg, but this can be selected.

The color can also be populated (it already is for out-of-the-box tables).

Currently, updating these doesn't work correctly (or at least instantly after a publish all), but I'd expect that this will be corrected shortly.

It would be great if this could be added into the Iconator tool please?

Many thanks, Alex

PS - I have huge appreciation for all the work you do on the XrmToolBox!

**Comment by MscrmTools** [comment]
I'm not sure to understand the request.
Setting an image and a color for the table is what iconator is made for so it has already these features
