### ISSUE TITLE
Web recourse Laoading

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/MscrmTools.Iconator#2]
Hi
i just want to tell you that there is small bug 
the loading window will not diaper after loading the web resources and it will keep loading
but still you can do your work and ignore it
Thanks and regards

**Comment by MscrmTools** [comment]
I guess you are using XrmToolBox 1.2016.10.2? If so, just download latest version and this problem will disappear

**Comment by aboodh95** [comment]
Yes i'm using the 1.2016.10.2
thank you
